### ISSUE TITLE
URL is broken for image in README

### ISSUE THREAD

**Issue by rnikoopour** [lk-geimfari/nebula#2]
Description is title.

**Comment by lk-geimfari** [comment]
@rnikoopour Sorry, but I do not quite understand. Can you clarify what you mean?

**Comment by rnikoopour** [comment]
@lk-geimfari 

Now that I reread my title it does seem rather vague.  Sorry about that.

In [this commit](https://github.com/lk-geimfari/nebula/commit/b494dae8c60642fafd04043e7215806c122a322b) you deleted `other/screen.png`

However, you're [README](https://github.com/lk-geimfari/nebula/commit/c8a79dd2e9396b3df67ff81c79856ae8897d182f) at master links to `other/screen.png`

```
### Screenshot

[Here](https://raw.githubusercontent.com/lk-geimfari/nebula/master/other/screen.png) you can find screenshot.
```

**Comment by lk-geimfari** [comment]
@rnikoopour After renaming the project we have mess in commits. Now i see. Thank you!
